package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class DashboardUtente {

    private JPanel dashboardUtente;
    private JLabel messaggioBenvenuto;
    private JPanel pannelloBottoni;
    private JButton hackatonDisponibili;
    private JButton iMieiTeam;
    private JButton iMieiHackaton;
    private JPanel pannelloLogic;
    private JScrollPane scrollPaneVisualizza;
    private JTextArea textAreaVisualizza;
    private JButton avantiButton;
    private JButton indietroButton;
    private JTextField fieldScrittura;
    private JButton iscrivitiButton;
    private JLabel AreaDiTesto;
    private JLabel messaggioErroreOrg;
    private JButton classificaButtonù;
    private JButton inviaInvitoButton;
    private JButton visualizzaInviti;

    public DashboardUtente(String emailUtente) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        dashboardUtente = new JPanel();
        dashboardUtente.setLayout(new BorderLayout(0, 0));
        dashboardUtente.setBackground(new Color(-15918294));
        dashboardUtente.setEnabled(true);
        dashboardUtente.setFocusCycleRoot(false);
        dashboardUtente.setMaximumSize(new Dimension(900, 600));
        dashboardUtente.setMinimumSize(new Dimension(900, 600));
        dashboardUtente.setPreferredSize(new Dimension(900, 600));
        pannelloBottoni = new JPanel();
        pannelloBottoni.setLayout(new GridLayoutManager(9, 1, new Insets(15, 15, 15, 15), -1, -1));
        pannelloBottoni.setBackground(new Color(-15918294));
        pannelloBottoni.setEnabled(true);
        dashboardUtente.add(pannelloBottoni, BorderLayout.EAST);
        pannelloBottoni.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final Spacer spacer1 = new Spacer();
        pannelloBottoni.add(spacer1, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        hackatonDisponibili = new JButton();
        hackatonDisponibili.setBackground(new Color(-13877680));
        hackatonDisponibili.setFocusable(false);
        Font hackatonDisponibiliFont = this.$$$getFont$$$("Inter", -1, -1, hackatonDisponibili.getFont());
        if (hackatonDisponibiliFont != null) hackatonDisponibili.setFont(hackatonDisponibiliFont);
        hackatonDisponibili.setForeground(new Color(-1));
        hackatonDisponibili.setHideActionText(false);
        hackatonDisponibili.setHorizontalTextPosition(4);
        hackatonDisponibili.setIconTextGap(6);
        hackatonDisponibili.setRequestFocusEnabled(true);
        hackatonDisponibili.setText("Hackaton Disponibili");
        pannelloBottoni.add(hackatonDisponibili, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        iMieiTeam = new JButton();
        iMieiTeam.setBackground(new Color(-13877680));
        iMieiTeam.setFocusable(false);
        Font iMieiTeamFont = this.$$$getFont$$$("Inter", -1, -1, iMieiTeam.getFont());
        if (iMieiTeamFont != null) iMieiTeam.setFont(iMieiTeamFont);
        iMieiTeam.setForeground(new Color(-1));
        iMieiTeam.setHorizontalTextPosition(4);
        iMieiTeam.setIconTextGap(6);
        iMieiTeam.setRequestFocusEnabled(true);
        iMieiTeam.setText("I miei Team");
        pannelloBottoni.add(iMieiTeam, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        iMieiHackaton = new JButton();
        iMieiHackaton.setBackground(new Color(-13877680));
        iMieiHackaton.setFocusable(false);
        Font iMieiHackatonFont = this.$$$getFont$$$("Inter", -1, -1, iMieiHackaton.getFont());
        if (iMieiHackatonFont != null) iMieiHackaton.setFont(iMieiHackatonFont);
        iMieiHackaton.setForeground(new Color(-1));
        iMieiHackaton.setHorizontalTextPosition(4);
        iMieiHackaton.setIconTextGap(6);
        iMieiHackaton.setRequestFocusEnabled(true);
        iMieiHackaton.setText("I miei Hackaton");
        pannelloBottoni.add(iMieiHackaton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setVisible(false);
        pannelloBottoni.add(panel1, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        messaggioBenvenuto = new JLabel();
        messaggioBenvenuto.setBackground(new Color(-15918294));
        Font messaggioBenvenutoFont = this.$$$getFont$$$("Inter", -1, 11, messaggioBenvenuto.getFont());
        if (messaggioBenvenutoFont != null) messaggioBenvenuto.setFont(messaggioBenvenutoFont);
        messaggioBenvenuto.setForeground(new Color(-1));
        messaggioBenvenuto.setIcon(new ImageIcon(getClass().getResource("/icone/icone bianche/icons8-user-40.png")));
        messaggioBenvenuto.setText("");
        pannelloBottoni.add(messaggioBenvenuto, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        classificaButtonù = new JButton();
        classificaButtonù.setBackground(new Color(-13877680));
        classificaButtonù.setFocusable(false);
        Font classificaButtonùFont = this.$$$getFont$$$("Inter", -1, -1, classificaButtonù.getFont());
        if (classificaButtonùFont != null) classificaButtonù.setFont(classificaButtonùFont);
        classificaButtonù.setForeground(new Color(-1));
        classificaButtonù.setHorizontalTextPosition(4);
        classificaButtonù.setIconTextGap(6);
        classificaButtonù.setRequestFocusEnabled(true);
        classificaButtonù.setText("Classifica");
        pannelloBottoni.add(classificaButtonù, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        inviaInvitoButton = new JButton();
        inviaInvitoButton.setBackground(new Color(-13877680));
        inviaInvitoButton.setFocusable(false);
        Font inviaInvitoButtonFont = this.$$$getFont$$$("Inter", -1, -1, inviaInvitoButton.getFont());
        if (inviaInvitoButtonFont != null) inviaInvitoButton.setFont(inviaInvitoButtonFont);
        inviaInvitoButton.setForeground(new Color(-1));
        inviaInvitoButton.setHorizontalTextPosition(4);
        inviaInvitoButton.setIconTextGap(6);
        inviaInvitoButton.setRequestFocusEnabled(true);
        inviaInvitoButton.setText("Invia Invito");
        pannelloBottoni.add(inviaInvitoButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        visualizzaInviti = new JButton();
        visualizzaInviti.setBackground(new Color(-13877680));
        visualizzaInviti.setFocusable(false);
        Font visualizzaInvitiFont = this.$$$getFont$$$("Inter", -1, -1, visualizzaInviti.getFont());
        if (visualizzaInvitiFont != null) visualizzaInviti.setFont(visualizzaInvitiFont);
        visualizzaInviti.setForeground(new Color(-1));
        visualizzaInviti.setHorizontalTextPosition(4);
        visualizzaInviti.setIconTextGap(6);
        visualizzaInviti.setRequestFocusEnabled(true);
        visualizzaInviti.setText("Visualizza Inviti");
        pannelloBottoni.add(visualizzaInviti, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        pannelloLogic = new JPanel();
        pannelloLogic.setLayout(new GridLayoutManager(4, 4, new Insets(15, 15, 15, 15), -1, -1));
        pannelloLogic.setBackground(new Color(-14540254));
        pannelloLogic.setEnabled(true);
        pannelloLogic.setForeground(new Color(-13947600));
        pannelloLogic.setMaximumSize(new Dimension(150, 70));
        pannelloLogic.setMinimumSize(new Dimension(150, 70));
        pannelloLogic.setPreferredSize(new Dimension(150, 70));
        pannelloLogic.setVisible(false);
        dashboardUtente.add(pannelloLogic, BorderLayout.CENTER);
        pannelloLogic.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        AreaDiTesto = new JLabel();
        AreaDiTesto.setBackground(new Color(-10658467));
        AreaDiTesto.setFocusable(true);
        Font AreaDiTestoFont = this.$$$getFont$$$("Inter", -1, 16, AreaDiTesto.getFont());
        if (AreaDiTestoFont != null) AreaDiTesto.setFont(AreaDiTestoFont);
        AreaDiTesto.setForeground(new Color(-1));
        AreaDiTesto.setText("Label");
        pannelloLogic.add(AreaDiTesto, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 200), new Dimension(200, 200), new Dimension(200, 200), 0, false));
        scrollPaneVisualizza = new JScrollPane();
        scrollPaneVisualizza.setFocusable(true);
        Font scrollPaneVisualizzaFont = this.$$$getFont$$$("Inter", -1, 14, scrollPaneVisualizza.getFont());
        if (scrollPaneVisualizzaFont != null) scrollPaneVisualizza.setFont(scrollPaneVisualizzaFont);
        scrollPaneVisualizza.setForeground(new Color(-1));
        scrollPaneVisualizza.setVisible(false);
        pannelloLogic.add(scrollPaneVisualizza, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(250, 400), new Dimension(250, 400), new Dimension(250, 400), 0, false));
        textAreaVisualizza = new JTextArea();
        textAreaVisualizza.setFocusable(true);
        Font textAreaVisualizzaFont = this.$$$getFont$$$("Inter", -1, 14, textAreaVisualizza.getFont());
        if (textAreaVisualizzaFont != null) textAreaVisualizza.setFont(textAreaVisualizzaFont);
        textAreaVisualizza.setForeground(new Color(-1));
        scrollPaneVisualizza.setViewportView(textAreaVisualizza);
        fieldScrittura = new JTextField();
        fieldScrittura.setBackground(new Color(-13877680));
        fieldScrittura.setFocusable(true);
        fieldScrittura.setForeground(new Color(-1));
        fieldScrittura.setSelectedTextColor(new Color(-1));
        pannelloLogic.add(fieldScrittura, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, 30), new Dimension(300, 30), new Dimension(300, 30), 0, false));
        messaggioErroreOrg = new JLabel();
        messaggioErroreOrg.setFocusable(true);
        messaggioErroreOrg.setText("Label");
        pannelloLogic.add(messaggioErroreOrg, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, new Dimension(300, 150), 0, false));
        indietroButton = new JButton();
        indietroButton.setBackground(new Color(-13877680));
        indietroButton.setFocusable(true);
        indietroButton.setForeground(new Color(-1));
        indietroButton.setText("Indietro");
        pannelloLogic.add(indietroButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_SOUTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 25), new Dimension(181, 25), new Dimension(100, 25), 1, false));
        avantiButton = new JButton();
        avantiButton.setBackground(new Color(-13877680));
        avantiButton.setFocusable(true);
        avantiButton.setForeground(new Color(-1));
        avantiButton.setText("Avanti");
        pannelloLogic.add(avantiButton, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_SOUTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 25), new Dimension(143, 25), new Dimension(100, 25), 0, false));
        iscrivitiButton = new JButton();
        iscrivitiButton.setBackground(new Color(-13877680));
        iscrivitiButton.setForeground(new Color(-1));
        iscrivitiButton.setText("Crea");
        iscrivitiButton.setVisible(false);
        pannelloLogic.add(iscrivitiButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 25), new Dimension(100, 25), new Dimension(100, 25), 0, false));
        final Spacer spacer2 = new Spacer();
        dashboardUtente.add(spacer2, BorderLayout.SOUTH);
        final Spacer spacer3 = new Spacer();
        dashboardUtente.add(spacer3, BorderLayout.NORTH);
        final Spacer spacer4 = new Spacer();
        dashboardUtente.add(spacer4, BorderLayout.WEST);
        messaggioBenvenuto.setLabelFor(scrollPaneVisualizza);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dashboardUtente;
    }

    public JPanel getDashboardUtente() {
        return dashboardUtente;
    }

    public JLabel getMessaggioBenvenuto() {
        return messaggioBenvenuto;
    }


    public JButton getHackatonDisponibili() {
        return hackatonDisponibili;
    }

    public JPanel getPannelloLogico() {
        return pannelloLogic;
    }

    public JScrollPane getScrollPaneVisualizza() {
        return scrollPaneVisualizza;
    }

    public JTextArea getTextAreaVisualizza() {
        return textAreaVisualizza;
    }

    public JButton getAvantiButton() {
        return avantiButton;
    }

    public JButton getIndietroButton() {
        return indietroButton;
    }

    public JTextField getFieldScrittura() {
        return fieldScrittura;
    }

    public JButton getIscrivitiButton() {
        return iscrivitiButton;
    }

    public JLabel getAreaDiTesto() {
        return AreaDiTesto;
    }

    public JLabel getMessaggioErroreOrg() {
        return messaggioErroreOrg;
    }

    public JButton getIMieiHackaton() {
        return iMieiHackaton;
    }


    public JButton getIMieiTeam() {
        return iMieiTeam;
    }

    public JButton getClassificaButton() {
        return classificaButtonù;
    }

    public JButton getInviaInvitoButton() {
        return inviaInvitoButton;
    }

    public JButton getVisualizzaInviti() {
        return visualizzaInviti;
    }

}

