package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class DashboardGiudice {
    private JPanel dashboardGiudice;
    private JLabel messaggioBenvenuto1;


    public DashboardGiudice(String emailGiudice) {

    }

    public JPanel getDashboardGiudice() {
        return dashboardGiudice;
    }

    public JLabel getMessaggioBenvenuto1() {
        return messaggioBenvenuto1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        dashboardGiudice = new JPanel();
        dashboardGiudice.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        dashboardGiudice.setBackground(new Color(-15918294));
        dashboardGiudice.setEnabled(false);
        Font dashboardGiudiceFont = this.$$$getFont$$$("Arial", -1, 14, dashboardGiudice.getFont());
        if (dashboardGiudiceFont != null) dashboardGiudice.setFont(dashboardGiudiceFont);
        dashboardGiudice.setForeground(new Color(-1));
        dashboardGiudice.setMaximumSize(new Dimension(700, 500));
        dashboardGiudice.setMinimumSize(new Dimension(700, 500));
        dashboardGiudice.setPreferredSize(new Dimension(700, 500));
        messaggioBenvenuto1 = new JLabel();
        messaggioBenvenuto1.setBackground(new Color(-15918294));
        Font messaggioBenvenuto1Font = this.$$$getFont$$$("Arial", -1, 14, messaggioBenvenuto1.getFont());
        if (messaggioBenvenuto1Font != null) messaggioBenvenuto1.setFont(messaggioBenvenuto1Font);
        messaggioBenvenuto1.setForeground(new Color(-1));
        messaggioBenvenuto1.setIcon(new ImageIcon(getClass().getResource("/icone/icons8-user-32.png")));
        messaggioBenvenuto1.setText("");
        dashboardGiudice.add(messaggioBenvenuto1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dashboardGiudice;
    }

}
