package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class DashboardGiudice {
    private JPanel dashboardGiudice;
    private JPanel pannelloBottoni;
    private JButton valutaTeamButton;
    private JButton hackatonAssegnati;
    private JLabel messaggioBenvenuto;
    private JButton classificaButtonù;
    private JButton visualizzaInvitiButton;
    private JPanel pannelloLogic;
    private JLabel AreaDiTesto;
    private JScrollPane scrollPaneVisualizza;
    private JTextArea textAreaVisualizza;
    private JTextField fieldScrittura;
    private JLabel messaggioErroreOrg;
    private JButton indietroButton;
    private JButton avantiButton;
    private JButton iscrivitiButton;


    public DashboardGiudice(String emailGiudice) {

    }

    public JPanel getDashboardGiudice() {
        return dashboardGiudice;
    }


    public JButton getVisualizzaInvitiButton() {
        return visualizzaInvitiButton;
    }

    public JScrollPane getScrollPaneVisualizza() {
        return scrollPaneVisualizza;
    }

    public JTextArea getTextAreaVisualizza() {
        return textAreaVisualizza;
    }

    public JLabel getMessaggioBenvenuto() {
        return messaggioBenvenuto;
    }

    public JPanel getPannelloLogico() {
        return pannelloLogic;
    }

    public JLabel getAreaDiTesto() {
        return AreaDiTesto;
    }

    public JLabel getMessaggioErroreOrg() {
        return messaggioErroreOrg;
    }

    public JTextField getFieldScrittura() {
        return fieldScrittura;
    }

    public JButton getAvantiButton() {
        return avantiButton;
    }

    public JButton getIndietroButton() {
        return indietroButton;
    }

    public JButton getIscrivitiButton() {
        return iscrivitiButton;
    }

    public JButton getIMieiTeam() {
        return valutaTeamButton;
    }

    public JButton getIMieiHackaton() {
        return hackatonAssegnati;
    }

    public JButton getClassificaButton() {
        return classificaButtonù;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        dashboardGiudice = new JPanel();
        dashboardGiudice.setLayout(new BorderLayout(0, 0));
        dashboardGiudice.setBackground(new Color(-15918294));
        dashboardGiudice.setEnabled(false);
        Font dashboardGiudiceFont = this.$$$getFont$$$("Arial", -1, 14, dashboardGiudice.getFont());
        if (dashboardGiudiceFont != null) dashboardGiudice.setFont(dashboardGiudiceFont);
        dashboardGiudice.setForeground(new Color(-1));
        dashboardGiudice.setMaximumSize(new Dimension(900, 600));
        dashboardGiudice.setMinimumSize(new Dimension(900, 600));
        dashboardGiudice.setPreferredSize(new Dimension(900, 600));
        final Spacer spacer1 = new Spacer();
        dashboardGiudice.add(spacer1, BorderLayout.SOUTH);
        final Spacer spacer2 = new Spacer();
        dashboardGiudice.add(spacer2, BorderLayout.NORTH);
        final Spacer spacer3 = new Spacer();
        dashboardGiudice.add(spacer3, BorderLayout.WEST);
        pannelloBottoni = new JPanel();
        pannelloBottoni.setLayout(new GridLayoutManager(6, 1, new Insets(15, 15, 15, 15), -1, -1));
        pannelloBottoni.setBackground(new Color(-15918294));
        pannelloBottoni.setEnabled(true);
        dashboardGiudice.add(pannelloBottoni, BorderLayout.EAST);
        pannelloBottoni.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final Spacer spacer4 = new Spacer();
        pannelloBottoni.add(spacer4, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        visualizzaInvitiButton = new JButton();
        visualizzaInvitiButton.setBackground(new Color(-13877680));
        visualizzaInvitiButton.setFocusable(false);
        Font visualizzaInvitiButtonFont = this.$$$getFont$$$("Inter", -1, -1, visualizzaInvitiButton.getFont());
        if (visualizzaInvitiButtonFont != null) visualizzaInvitiButton.setFont(visualizzaInvitiButtonFont);
        visualizzaInvitiButton.setForeground(new Color(-1));
        visualizzaInvitiButton.setHideActionText(false);
        visualizzaInvitiButton.setHorizontalTextPosition(4);
        visualizzaInvitiButton.setIconTextGap(6);
        visualizzaInvitiButton.setRequestFocusEnabled(true);
        visualizzaInvitiButton.setText("Visualizza Inviti");
        pannelloBottoni.add(visualizzaInvitiButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        valutaTeamButton = new JButton();
        valutaTeamButton.setBackground(new Color(-13877680));
        valutaTeamButton.setFocusable(false);
        Font valutaTeamButtonFont = this.$$$getFont$$$("Inter", -1, -1, valutaTeamButton.getFont());
        if (valutaTeamButtonFont != null) valutaTeamButton.setFont(valutaTeamButtonFont);
        valutaTeamButton.setForeground(new Color(-1));
        valutaTeamButton.setHorizontalTextPosition(4);
        valutaTeamButton.setIconTextGap(6);
        valutaTeamButton.setRequestFocusEnabled(true);
        valutaTeamButton.setText("Valuta un Team");
        pannelloBottoni.add(valutaTeamButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        hackatonAssegnati = new JButton();
        hackatonAssegnati.setBackground(new Color(-13877680));
        hackatonAssegnati.setFocusable(false);
        Font hackatonAssegnatiFont = this.$$$getFont$$$("Inter", -1, -1, hackatonAssegnati.getFont());
        if (hackatonAssegnatiFont != null) hackatonAssegnati.setFont(hackatonAssegnatiFont);
        hackatonAssegnati.setForeground(new Color(-1));
        hackatonAssegnati.setHorizontalTextPosition(4);
        hackatonAssegnati.setIconTextGap(6);
        hackatonAssegnati.setRequestFocusEnabled(true);
        hackatonAssegnati.setText("Hackaton assegnati");
        pannelloBottoni.add(hackatonAssegnati, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        messaggioBenvenuto = new JLabel();
        messaggioBenvenuto.setBackground(new Color(-15918294));
        Font messaggioBenvenutoFont = this.$$$getFont$$$("Inter", -1, 11, messaggioBenvenuto.getFont());
        if (messaggioBenvenutoFont != null) messaggioBenvenuto.setFont(messaggioBenvenutoFont);
        messaggioBenvenuto.setForeground(new Color(-1));
        messaggioBenvenuto.setIcon(new ImageIcon(getClass().getResource("/icone/icone bianche/icons8-user-40.png")));
        messaggioBenvenuto.setText("");
        pannelloBottoni.add(messaggioBenvenuto, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        classificaButtonù = new JButton();
        classificaButtonù.setBackground(new Color(-13877680));
        classificaButtonù.setFocusable(false);
        Font classificaButtonùFont = this.$$$getFont$$$("Inter", -1, -1, classificaButtonù.getFont());
        if (classificaButtonùFont != null) classificaButtonù.setFont(classificaButtonùFont);
        classificaButtonù.setForeground(new Color(-1));
        classificaButtonù.setHorizontalTextPosition(4);
        classificaButtonù.setIconTextGap(6);
        classificaButtonù.setRequestFocusEnabled(true);
        classificaButtonù.setText("Classifica");
        pannelloBottoni.add(classificaButtonù, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(175, 35), new Dimension(175, 35), new Dimension(175, 35), 0, false));
        pannelloLogic = new JPanel();
        pannelloLogic.setLayout(new GridLayoutManager(4, 4, new Insets(15, 15, 15, 15), -1, -1));
        pannelloLogic.setBackground(new Color(-14540254));
        pannelloLogic.setEnabled(true);
        pannelloLogic.setForeground(new Color(-13947600));
        pannelloLogic.setMaximumSize(new Dimension(150, 70));
        pannelloLogic.setMinimumSize(new Dimension(150, 70));
        pannelloLogic.setPreferredSize(new Dimension(150, 70));
        pannelloLogic.setVisible(false);
        dashboardGiudice.add(pannelloLogic, BorderLayout.CENTER);
        pannelloLogic.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        AreaDiTesto = new JLabel();
        AreaDiTesto.setBackground(new Color(-10658467));
        AreaDiTesto.setFocusable(true);
        Font AreaDiTestoFont = this.$$$getFont$$$("Inter", -1, 16, AreaDiTesto.getFont());
        if (AreaDiTestoFont != null) AreaDiTesto.setFont(AreaDiTestoFont);
        AreaDiTesto.setForeground(new Color(-1));
        AreaDiTesto.setText("Label");
        pannelloLogic.add(AreaDiTesto, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(200, 200), new Dimension(200, 200), new Dimension(200, 200), 0, false));
        scrollPaneVisualizza = new JScrollPane();
        scrollPaneVisualizza.setFocusable(true);
        Font scrollPaneVisualizzaFont = this.$$$getFont$$$("Inter", -1, 14, scrollPaneVisualizza.getFont());
        if (scrollPaneVisualizzaFont != null) scrollPaneVisualizza.setFont(scrollPaneVisualizzaFont);
        scrollPaneVisualizza.setForeground(new Color(-1));
        scrollPaneVisualizza.setVisible(false);
        pannelloLogic.add(scrollPaneVisualizza, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(250, 400), new Dimension(250, 400), new Dimension(250, 400), 0, false));
        textAreaVisualizza = new JTextArea();
        textAreaVisualizza.setFocusable(true);
        Font textAreaVisualizzaFont = this.$$$getFont$$$("Inter", -1, 14, textAreaVisualizza.getFont());
        if (textAreaVisualizzaFont != null) textAreaVisualizza.setFont(textAreaVisualizzaFont);
        textAreaVisualizza.setForeground(new Color(-1));
        scrollPaneVisualizza.setViewportView(textAreaVisualizza);
        fieldScrittura = new JTextField();
        fieldScrittura.setBackground(new Color(-13877680));
        fieldScrittura.setFocusable(true);
        fieldScrittura.setForeground(new Color(-1));
        fieldScrittura.setSelectedTextColor(new Color(-1));
        pannelloLogic.add(fieldScrittura, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(300, 30), new Dimension(300, 30), new Dimension(300, 30), 0, false));
        messaggioErroreOrg = new JLabel();
        messaggioErroreOrg.setFocusable(true);
        messaggioErroreOrg.setText("Label");
        pannelloLogic.add(messaggioErroreOrg, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, new Dimension(300, 150), 0, false));
        indietroButton = new JButton();
        indietroButton.setBackground(new Color(-13877680));
        indietroButton.setFocusable(true);
        indietroButton.setForeground(new Color(-1));
        indietroButton.setText("Indietro");
        pannelloLogic.add(indietroButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_SOUTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 25), new Dimension(181, 25), new Dimension(100, 25), 1, false));
        avantiButton = new JButton();
        avantiButton.setBackground(new Color(-13877680));
        avantiButton.setFocusable(true);
        avantiButton.setForeground(new Color(-1));
        avantiButton.setText("Avanti");
        pannelloLogic.add(avantiButton, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_SOUTHEAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 25), new Dimension(143, 25), new Dimension(100, 25), 0, false));
        iscrivitiButton = new JButton();
        iscrivitiButton.setBackground(new Color(-13877680));
        iscrivitiButton.setForeground(new Color(-1));
        iscrivitiButton.setText("Crea");
        iscrivitiButton.setVisible(false);
        pannelloLogic.add(iscrivitiButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 25), new Dimension(100, 25), new Dimension(100, 25), 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return dashboardGiudice;
    }

}
